
services:
  my_cruise_app:
    image: cruise-ai-agent-api:latest
    container_name: cruise_app
    restart: unless-stopped
    volumes:
      - ./secret/service-account-key.json:/app/service-account-key.json:ro
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      GCS_BUCKET_NAME: ${GCS_BUCKET_NAME}
      GOOGLE_APPLICATION_CREDENTIALS: /app/service-account-key.json
      CHROMA_DATA_DIR: ${CHROMA_DATA_DIR}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      FIRESTORE_PROJECT_ID: ${FIRESTORE_PROJECT_ID}
      POSTGRES_DB_URL: ${POSTGRES_DB_URL}
    ports:
      - "8000:8080"
