version: '3.8'

services:
  cruise-ai-agent-extractor:
    image: cruise-ai-agent-extractor
    volumes:
      - ./secret/service-account-key.json:/app/service-account-key.json:ro
    environment:
      GCS_BUCKET_NAME: ${GCS_BUCKET_NAME}
      GOOGLE_APPLICATION_CREDENTIALS: /app/service-account-key.json
      CHROMA_DATA_DIR: ${CHROMA_DATA_DIR}
      SQLITE_DB_PATH: ${SQLITE_DB_PATH}
      POSTGRES_DB_URL: ${POSTGRES_DB_URL}
      FIRESTORE_PROJECT_ID: ${FIRESTORE_PROJECT_ID}
